name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo ./bootstrap.sh

    - name: Run
      run: ./build.sh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-bin
        path: |
          build/*
